# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        # self.setWindowIcon()
        Form.setObjectName("Form")
        Form.resize(911, 492)
        Form.setStyleSheet("\n"
                           "QToolTip{background: #191c22; color:white; border:1px solid #5a616f}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.container = QtWidgets.QFrame(Form)
        self.container.setStyleSheet("QFrame#container{\n"
                                     "background-color: rgb(243, 243, 243);\n"
                                     "border:2px solid rgb(0, 208, 255);\n"
                                     "}\n"
                                     "\n"
                                     "")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.gridLayout = QtWidgets.QGridLayout(self.container)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.navBar = QtWidgets.QFrame(self.container)
        self.navBar.setStyleSheet("QFrame{\n"
                                  "background-color: #0f1014;\n"
                                  "border:0px;\n"
                                  "}")
        self.navBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navBar.setObjectName("navBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.navBar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.expandBtn = QtWidgets.QPushButton(self.navBar)
        self.expandBtn.setMinimumSize(QtCore.QSize(45, 45))
        self.expandBtn.setMaximumSize(QtCore.QSize(45, 45))
        self.expandBtn.setStyleSheet("QPushButton{\n"
                                     "border:0px;\n"
                                     "width:10;\n"
                                     "}\n"
                                     "QPushButton::hover{\n"
                                     "background-color: rgb(40, 44, 54);\n"
                                     "}\n"
                                     "QPushButton::checked{\n"
                                     "background-color: #191c22;\n"
                                     "}\n"
                                     "")
        self.expandBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/hamburger.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.expandBtn.setIcon(icon)
        self.expandBtn.setIconSize(QtCore.QSize(40, 40))
        self.expandBtn.setCheckable(True)
        self.expandBtn.setObjectName("expandBtn")
        self.verticalLayout_2.addWidget(self.expandBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.settingBtn = QtWidgets.QPushButton(self.navBar)
        self.settingBtn.setMinimumSize(QtCore.QSize(45, 45))
        self.settingBtn.setMaximumSize(QtCore.QSize(45, 45))
        self.settingBtn.setStyleSheet("QPushButton{\n"
                                      "border:0px;\n"
                                      "width:10;\n"
                                      "}\n"
                                      "QPushButton::hover{\n"
                                      "background-color: #191c22;\n"
                                      "}\n"
                                      "QPushButton::checked{\n"
                                      "\n"
                                      "background-color: rgb(40, 44, 54);\n"
                                      "}")
        self.settingBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/setings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingBtn.setIcon(icon1)
        self.settingBtn.setIconSize(QtCore.QSize(24, 24))
        self.settingBtn.setCheckable(True)
        self.settingBtn.setChecked(True)
        self.settingBtn.setObjectName("settingBtn")
        self.verticalLayout_2.addWidget(self.settingBtn)
        self.gridLayout.addWidget(self.navBar, 1, 0, 1, 1)
        self.menuBar = QtWidgets.QFrame(self.container)
        self.menuBar.setStyleSheet("QFrame#menuBar{\n"
                                   "background-color: #0f1014;\n"
                                   "border:0px;\n"
                                   "}")
        self.menuBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuBar.setObjectName("menuBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menuBar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.appName = QtWidgets.QLabel(self.menuBar)
        self.appName.setStyleSheet("font: 11pt \"Yu Gothic UI\";\n"
                                   "color:white;")
        self.appName.setObjectName("appName")
        self.horizontalLayout_2.addWidget(self.appName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.minBtn = QtWidgets.QPushButton(self.menuBar)
        self.minBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.minBtn.setMaximumSize(QtCore.QSize(45, 35))
        self.minBtn.setStyleSheet("QPushButton{\n"
                                  "border:0px;\n"
                                  "}\n"
                                  "QPushButton::hover{\n"
                                  "background-color: rgb(0, 208, 255);\n"
                                  "}\n"
                                  "QPushButton::pressed{\n"
                                  "background-color: rgba(0, 208, 255, 200);\n"
                                  "}\n"
                                  "")
        self.minBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icons/minimaze.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minBtn.setIcon(icon2)
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout_2.addWidget(self.minBtn)
        self.restoreBtn = QtWidgets.QPushButton(self.menuBar)
        self.restoreBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.restoreBtn.setMaximumSize(QtCore.QSize(45, 35))
        self.restoreBtn.setStyleSheet("QPushButton{\n"
                                      "border:0px;\n"
                                      "}\n"
                                      "QPushButton::hover{\n"
                                      "background-color: rgb(0, 208, 255);\n"
                                      "}\n"
                                      "QPushButton::checked{\n"
                                      "background-color: rgb(0, 208, 255);\n"
                                      "}\n"
                                      "")
        self.restoreBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./icons/maximaze.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreBtn.setIcon(icon3)
        self.restoreBtn.setCheckable(True)
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_2.addWidget(self.restoreBtn)
        self.exitBtn = QtWidgets.QPushButton(self.menuBar)
        self.exitBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.exitBtn.setMaximumSize(QtCore.QSize(45, 35))
        self.exitBtn.setStyleSheet("QPushButton{\n"
                                   "border:0px;\n"
                                   "}\n"
                                   "QPushButton::hover{\n"
                                   "background-color: rgb(0, 208, 255);\n"
                                   "}\n"
                                   "QPushButton::pressed{\n"
                                   "background-color: rgba(0, 208, 255, 200);\n"
                                   "}\n"
                                   "")
        self.exitBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon4)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_2.addWidget(self.exitBtn)
        self.gridLayout.addWidget(self.menuBar, 0, 1, 1, 2)
        self.logoFrame = QtWidgets.QFrame(self.container)
        self.logoFrame.setMinimumSize(QtCore.QSize(45, 35))
        self.logoFrame.setMaximumSize(QtCore.QSize(45, 35))
        self.logoFrame.setStyleSheet("background-color: #0f1014;\n"
                                     "")
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.logoFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QPushButton(self.logoFrame)
        self.logo.setEnabled(False)
        self.logo.setMinimumSize(QtCore.QSize(45, 35))
        self.logo.setMaximumSize(QtCore.QSize(45, 35))
        self.logo.setStyleSheet("border-bottom:1px solid rgb(213, 213, 213)")
        self.logo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./icons/hospital.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo.setIcon(icon5)
        self.logo.setIconSize(QtCore.QSize(32, 32))
        self.logo.setAutoRepeatDelay(301)
        self.logo.setFlat(True)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.gridLayout.addWidget(self.logoFrame, 0, 0, 1, 1)
        self.optionBar = QtWidgets.QFrame(self.container)
        self.optionBar.setEnabled(True)
        self.optionBar.setMinimumSize(QtCore.QSize(0, 0))
        self.optionBar.setMaximumSize(QtCore.QSize(0, 16777215))
        self.optionBar.setStyleSheet("QFrame{background: #191c22;\n"
                                     "border:0px;}\n"
                                     "\n"
                                     "QScrollBar:horizontal\n"
                                     "    {\n"
                                     "        height: 15px;\n"
                                     "        margin: 3px 15px 3px 15px;\n"
                                     "        border: 1px transparent #2A2929;\n"
                                     "        border-radius: 4px;\n"
                                     "        background-color: rgba(0, 0, 0,0);\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::handle:horizontal\n"
                                     "    {\n"
                                     "         background-color: rgb(0, 230, 255);\n"
                                     "        min-width: 5px;\n"
                                     "        border-radius: 4px;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::add-line:horizontal\n"
                                     "    {\n"
                                     "        margin: 0px 3px 0px 3px;\n"
                                     "        border-image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
                                     "        width: 10px;\n"
                                     "        height: 10px;\n"
                                     "        subcontrol-position: right;\n"
                                     "        subcontrol-origin: margin;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::sub-line:horizontal\n"
                                     "    {\n"
                                     "        margin: 0px 3px 0px 3px;\n"
                                     "        border-image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
                                     "        height: 10px;\n"
                                     "        width: 10px;\n"
                                     "        subcontrol-position: left;\n"
                                     "        subcontrol-origin: margin;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::add-line:horizontal:hover,QScrollBar::add-line:horizontal:on\n"
                                     "    {\n"
                                     "        border-image: url(:/qss_icons/rc/right_arrow.png);\n"
                                     "        height: 10px;\n"
                                     "        width: 10px;\n"
                                     "        subcontrol-position: right;\n"
                                     "        subcontrol-origin: margin;\n"
                                     "    }\n"
                                     "\n"
                                     "\n"
                                     "    QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on\n"
                                     "    {\n"
                                     "        border-image: url(:/qss_icons/rc/left_arrow.png);\n"
                                     "        height: 10px;\n"
                                     "        width: 10px;\n"
                                     "        subcontrol-position: left;\n"
                                     "        subcontrol-origin: margin;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
                                     "    {\n"
                                     "        background: none;\n"
                                     "    }\n"
                                     "\n"
                                     "\n"
                                     "    QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                                     "    {\n"
                                     "        background: none;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar:vertical\n"
                                     "    {\n"
                                     "         background-color: none;\n"
                                     "        width: 15px;\n"
                                     "        margin: 15px 3px 15px 3px;\n"
                                     "        border: 1px transparent #2A2929;\n"
                                     "        border-radius: 4px;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::handle:vertical\n"
                                     "    {\n"
                                     "        background-color: rgb(0, 230, 255);\n"
                                     "        min-height: 5px;\n"
                                     "\n"
                                     "        border-radius: 4px;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::sub-line:vertical\n"
                                     "    {\n"
                                     "        margin: 3px 0px 3px 0px;\n"
                                     "        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
                                     "        height: 10px;\n"
                                     "        width: 10px;\n"
                                     "        subcontrol-position: top;\n"
                                     "        subcontrol-origin: margin;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::add-line:vertical\n"
                                     "    {\n"
                                     "        margin: 3px 0px 3px 0px;\n"
                                     "        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
                                     "        height: 10px;\n"
                                     "        width: 10px;\n"
                                     "        subcontrol-position: bottom;\n"
                                     "        subcontrol-origin: margin;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
                                     "    {\n"
                                     "        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
                                     "        height: 10px;\n"
                                     "        width: 10px;\n"
                                     "        subcontrol-position: top;\n"
                                     "        subcontrol-origin: margin;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
                                     "    {\n"
                                     "        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
                                     "        height: 10px;\n"
                                     "        width: 10px;\n"
                                     "        subcontrol-position: bottom;\n"
                                     "        subcontrol-origin: margin;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
                                     "    {\n"
                                     "        background: none;\n"
                                     "    }\n"
                                     "\n"
                                     "    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                                     "    {\n"
                                     "        background: none;\n"
                                     "    }")
        self.optionBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.optionBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.optionBar.setObjectName("optionBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.optionBar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        # ----------------------------------------------------------------------
        #                   Show lists button
        # ----------------------------------------------------------------------
        self.department = QtWidgets.QPushButton(self.optionBar)
        self.department.setToolTip("Show Departments Date")
        self.department.setMinimumSize(QtCore.QSize(44, 45))
        self.department.setMaximumSize(QtCore.QSize(230, 58))
        self.department.setStyleSheet("QPushButton{\n"   
                                      "background-color: #54D3F3;\n"
                                      "border:14px;\n"
                                      "border-radius: 30px;\n"
                                      "width:10;\n"
                                      "font: 15pt;\n"
                                      "border-bottom: 3px solid rgb(40, 44, 84);\n"
                                      "}\n"
                                      "QPushButton::hover{\n"
                                      "background-color: rgb(40, 44, 84);\n"
                                      "}\n"
                                      "QPushButton::pressed{\n"
                                      "background-color: #191c22;\n"
                                      "url:(/home/arsen/Downloads/icons/png);\n"
                                      "}\n")

        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./icons/png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.department.setIcon(icon6)
        self.department.setText("Departments")
        self.department.setIconSize(QtCore.QSize(30, 30))
        self.department.setCheckable(True)
        self.department.setObjectName("department")
        self.gridLayout_3.addWidget(self.department, 3, 0, 1, 1)
        self.gridLayout_3.setSpacing(20)

        self.service = QtWidgets.QPushButton(self.optionBar)
        self.service.setToolTip("Show Services Date")
        self.service.setMinimumSize(QtCore.QSize(44, 45))
        self.service.setMaximumSize(QtCore.QSize(230, 58))
        self.service.setStyleSheet("QPushButton{\n"
                                    "border-radius:30px;\n"
                                    "background-color: #54D3F3;\n"
                                    "border:14px;\n"
                                    "width:10;\n"
                                    "font: 15pt;\n"
                                    "border-bottom: 1px solid rgb(40, 44, 84);\n"
                                    "}\n"
                                    "QPushButton::hover{\n"
                                    "background-color: rgb(40, 44, 84);\n"
                                    "}\n"
                                    "QPushButton::pressed{\n"
                                    "background-color: #191c22;\n"
                                    "url:(./icons/service.png);\n"
                                    "}\n")

        icon_service = QtGui.QIcon()
        icon_service.addPixmap(QtGui.QPixmap("./icons/service.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.service.setIcon(icon_service)
        self.service.setText("Services")
        self.service.setIconSize(QtCore.QSize(30, 30))
        self.service.setCheckable(True)
        self.service.setObjectName("services")
        self.gridLayout_3.addWidget(self.service, 4, 0, 1, 1)

        self.staf = QtWidgets.QPushButton(self.optionBar)
        self.staf.setToolTip("Show Staff Date")
        self.staf.setMinimumSize(QtCore.QSize(44, 45))
        self.staf.setMaximumSize(QtCore.QSize(230, 58))
        self.staf.setStyleSheet("QPushButton{\n"
                                "background-color: #54D3F3;\n"
                                "border-radius:30px;\n"
                                "border:14px;\n"
                                "width:10;\n"
                                "font: 15pt;\n"
                                "border-bottom: 1px solid rgb(40, 44, 84);\n"
                                "}\n"
                                "QPushButton::hover{\n"
                                "background-color: rgb(40, 44, 84);\n"
                                "}\n"
                                "QPushButton::pressed{\n"
                                "background-color: #191c22;\n"
                                "url:(./icons/doctor.png);\n"
                                "}\n")

        icon_staf = QtGui.QIcon()
        icon_staf.addPixmap(QtGui.QPixmap("./icons/doctor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.staf.setIcon(icon_staf)
        self.staf.setText("Staff")
        self.staf.setIconSize(QtCore.QSize(30, 30))
        self.staf.setCheckable(True)
        self.staf.setObjectName("staff")
        self.gridLayout_3.addWidget(self.staf, 5, 0, 1, 1)

        self.patients = QtWidgets.QPushButton(self.optionBar)
        self.patients.setToolTip("Show Patients Date")
        self.patients.setMinimumSize(QtCore.QSize(44, 45))
        self.patients.setMaximumSize(QtCore.QSize(230, 58))
        self.patients.setStyleSheet("QPushButton{\n"
                                    "background-color: #54D3F3;\n"
                                    "border:14px;\n"
                                    "border-radius:30px;\n"
                                    "width:10;\n"
                                    "font: 15pt;\n"
                                    "border-bottom: 1px solid rgb(40, 44, 84);\n"
                                    "}\n"
                                    "QPushButton::hover{\n"
                                    "background-color: rgb(40, 44, 84);\n"
                                    "}\n"
                                    "QPushButton::pressed{\n"
                                    "background-color: #191c22;\n"
                                    "url:(./icons/patient.png);\n"
                                    "}\n")

        icon_patients = QtGui.QIcon()
        icon_patients.addPixmap(QtGui.QPixmap("./icons/patient.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patients.setIcon(icon_patients)
        self.patients.setText("Patients")
        self.patients.setIconSize(QtCore.QSize(30, 30))
        self.patients.setCheckable(True)
        self.patients.setObjectName("patients")
        self.gridLayout_3.addWidget(self.patients, 6, 0, 1, 1)

        self.room = QtWidgets.QPushButton(self.optionBar)
        self.room.setToolTip("Show Rooms Date")
        self.room.setMinimumSize(QtCore.QSize(44, 45))
        self.room.setMaximumSize(QtCore.QSize(230, 58))
        self.room.setStyleSheet("QPushButton{\n"
                                "background-color: #54D3F3;\n"
                                "border-radius:30px;\n"
                                "border:14px;\n"
                                "width:10;\n"
                                "font: 15pt;\n"
                                "border-bottom: 1px solid rgb(40, 44, 84);\n"
                                "}\n"
                                "QPushButton::hover{\n"
                                "background-color: rgb(40, 44, 84);\n"
                                "}\n"
                                "QPushButton::pressed{\n"
                                "background-color: #191c22;\n"
                                "url:(./icons/room.png);\n"
                                "}\n")

        icon_room = QtGui.QIcon()
        icon_room.addPixmap(QtGui.QPixmap("./icons/room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.room.setIcon(icon_room)
        self.room.setText("Rooms")
        self.room.setIconSize(QtCore.QSize(30, 30))
        self.room.setCheckable(True)
        self.room.setObjectName("room")
        self.gridLayout_3.addWidget(self.room, 7, 0, 1, 1)

        self.all = QtWidgets.QPushButton(self.optionBar)
        self.all.setToolTip("Other Types")
        self.all.setMinimumSize(QtCore.QSize(44, 45))
        self.all.setMaximumSize(QtCore.QSize(230, 58))
        self.all.setStyleSheet("QPushButton{\n"
                                "background-color: #54D3F3;\n"
                                "border-radius:30px;\n"
                                "border:14px;\n"
                                "width:10;\n"
                                "font: 15pt;\n"
                                "border-bottom: 1px solid rgb(40, 44, 84);\n"
                                "}\n"
                                "QPushButton::hover{\n"
                                "background-color: rgb(40, 44, 84);\n"
                                "}\n"
                                "QPushButton::pressed{\n"
                                "background-color: #191c22;\n"
                                "url:(./icons/room.png);\n"
                                "}\n")

        icon_room = QtGui.QIcon()
        icon_room.addPixmap(QtGui.QPixmap("./icons/all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.all.setIcon(icon_room)
        self.all.setText("All Lists")
        self.all.setIconSize(QtCore.QSize(30, 30))
        self.all.setCheckable(True)
        self.all.setObjectName("all")
        self.gridLayout_3.addWidget(self.all, 8, 0, 1, 1)

        # ----------------------------------------------------------------------
        #                   Secret Manu
        # ==================================================================

        self.lineEdit = QtWidgets.QTextBrowser(self.optionBar)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEdit.setMaximumSize(QtCore.QSize(280, 30))
        self.lineEdit.setText("Hospital Managment")
        self.lineEdit.setStyleSheet("QTextBrowser{\n"
                                    "border:0px;\n"
                                    "border-radius:50px;\n"
                                    "background: rgb(0, 144, 177);\n"
                                    "border-bottom: 1px solid rgb(40, 44, 54);\n"
                                    "    color: rgb(0, 230, 255);\n"
                                    "    font: 350 15pt \"Yu Gothic UI Semilight\";\n"
                                    "}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.treeView = QtWidgets.QTreeView(self.optionBar)
        self.treeView.setStyleSheet("QTreeView{background: #191c22; color:white}\n"
                                    "\n"
                                    "QTreeView::item::hover{border-left:2px solid white; background:#5a616f}\n"
                                    "QTreeView::item::selected{border-left:3px solid  rgb(0, 208, 255);color:white}\n"
                                    "QTreeView::item {border-left: 1px solid #5a616f}")
        self.treeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeView.setDragEnabled(True)
        self.treeView.setDragDropOverwriteMode(True)
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.treeView)
        self.gridLayout.addWidget(self.optionBar, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.container)
        self.frame_4.setStyleSheet("border:0px;\n"
                                   "background-color: rgb(40, 44, 54);\n"
                                   "iconify:{icon: dash:admin-generic; color: white; size: 32;"
                                   "animation: breathe; animateOn: hover}\n")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calculate = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate.sizePolicy().hasHeightForWidth())
        # =====================================================================
        #                   Buttons Manu
        # ====================================================================

        self.calculate.setSizePolicy(sizePolicy)
        self.calculate.setToolTip("Calculate price of services")
        self.calculate.setMinimumSize(QtCore.QSize(183, 197))
        self.calculate.setStyleSheet("QPushButton{\n"
                                     "border-radius:50px;\n"
                                     "font: 63 italic 11pt \"URW Bookman\";\n"
                                     "background:rgb(0, 144, 177);}\n"
                                     "QPushButton::hover{\n"
                                     "background-color: rgb(40, 44, 84);}\n"
                                     "QPushButton::pressed{\n"
                                     "background-color: #191c22;}\n"
                                     "url:(./icons/calculate.png);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./icons/calculate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.calculate.setIcon(icon7)
        self.calculate.setIconSize(QtCore.QSize(70, 70))
        self.calculate.setObjectName("calculate")
        self.gridLayout_2.addWidget(self.calculate, 1, 3, 1, 1)

        self.insert = QtWidgets.QPushButton(self.groupBox)
        self.insert.setToolTip("Add Data in the server")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insert.sizePolicy().hasHeightForWidth())
        self.insert.setSizePolicy(sizePolicy)
        self.insert.setStyleSheet("QPushButton{\n"
                                  "border-radius:50px;\n"
                                  "font: 63 italic 11pt \"URW Bookman\";\n"
                                  "background:rgb(0, 144, 177);}\n"
                                  "QPushButton::hover{\n"
                                  "background-color: rgb(40, 44, 84);}\n"
                                  "QPushButton::pressed{\n"
                                  "background-color: #191c22;}\n")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./icons/insert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insert.setIcon(icon8)
        self.insert.setIconSize(QtCore.QSize(80, 80))
        self.insert.setObjectName("insert")
        self.gridLayout_2.addWidget(self.insert, 1, 0, 1, 1)

        self.show_list = QtWidgets.QPushButton(self.groupBox)
        self.show_list.setToolTip("Show Date")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_list.sizePolicy().hasHeightForWidth())
        self.show_list.setSizePolicy(sizePolicy)
        self.show_list.setBaseSize(QtCore.QSize(40, 40))
        self.show_list.setStyleSheet("QPushButton{\n"
                                     "border-radius:50px;\n"
                                     "font: 63 italic 11pt \"URW Bookman\";\n"
                                     "background:rgb(0, 144, 177);\n"
                                     "url:(/home/arsen/Downloads/icons/list.png);}\n"
                                     "QPushButton::hover{\n"
                                     "background-color: rgb(40, 44, 84);}\n"
                                     "QPushButton::pressed{\n"
                                     "background-color: #191c22;}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./icons/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.show_list.setIcon(icon9)
        self.show_list.setIconSize(QtCore.QSize(80, 80))
        self.show_list.setCheckable(False)
        self.show_list.setAutoRepeat(False)
        self.show_list.setAutoDefault(False)
        self.show_list.setObjectName("show_list")
        self.gridLayout_2.addWidget(self.show_list, 0, 0, 1, 1)

        self.data_update = QtWidgets.QPushButton(self.groupBox)
        self.data_update.setToolTip("Update Date")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_update.sizePolicy().hasHeightForWidth())
        self.data_update.setSizePolicy(sizePolicy)
        self.data_update.setStyleSheet("QPushButton{\n"
                                       "border-radius:50px;\n"
                                       "font: 63 italic 12pt \"URW Bookman\";\n"
                                       "background:rgb(0, 144, 177);}\n"
                                       "QPushButton::hover{\n"
                                       "background-color: rgb(40, 44, 84);}\n"
                                       "QPushButton::pressed{\n"
                                       "background-color: #191c22;}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("./icons/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.data_update.setIcon(icon10)
        self.data_update.setIconSize(QtCore.QSize(70, 70))
        self.data_update.setObjectName("data_update")
        self.gridLayout_2.addWidget(self.data_update, 0, 3, 1, 1)

        self.search = QtWidgets.QPushButton(self.groupBox)
        self.search.setToolTip("Search Function")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search.sizePolicy().hasHeightForWidth())
        self.search.setSizePolicy(sizePolicy)
        self.search.setMouseTracking(True)
        self.search.setTabletTracking(True)
        self.search.setStyleSheet("QPushButton{\n"
                                  "border-radius:50px;\n"
                                  "font: 63 italic 11pt \"URW Bookman\";\n"
                                  "background:rgb(0, 144, 177);}\n"
                                  "QPushButton::hover{\n"
                                  "background-color: rgb(40, 44, 84);}\n"
                                  "QPushButton::pressed{\n"
                                  "background-color: #191c22;}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("./icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search.setIcon(icon11)
        self.search.setIconSize(QtCore.QSize(80, 80))
        self.search.setObjectName("search")
        self.gridLayout_2.addWidget(self.search, 0, 4, 1, 1)

        self.exit = QtWidgets.QPushButton(self.groupBox)
        self.exit.setToolTip("Exit from application")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit.sizePolicy().hasHeightForWidth())
        self.exit.setSizePolicy(sizePolicy)
        self.exit.setStyleSheet("QPushButton{\n"
                                "border-radius:50px;\n"
                                "font: 63 italic 12pt \"URW Bookman\";\n"
                                "background:rgb(0, 144, 177);}\n"
                                "QPushButton::hover{\n"
                                "background-color: rgb(40, 44, 84);}\n"
                                "QPushButton::pressed{\n"
                                "background-color: #191c22;}\n")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("./icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon12)
        self.exit.setIconSize(QtCore.QSize(80, 80))
        self.exit.setObjectName("exit")
        self.gridLayout_2.addWidget(self.exit, 1, 4, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 251, 196))
        self.frame_2.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gif_label = QtWidgets.QLabel(self.frame_2)
        self.gif_label.setFixedSize(250, 200)
        self.gif = QtGui.QMovie("./icons/hospital_gif1.gif")
        self.gif_label.setMovie(self.gif)
        # self.gif.setScaledSize([250, 200])
        self.gif.start()
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_3)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 216, 251, 168))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMinimumSize(QtCore.QSize(50, 50))
        self.calendarWidget.setDateEditAcceptDelay(1000)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 1, 2, 1, 1)
        self.optionBar.raise_()
        self.navBar.raise_()
        self.menuBar.raise_()
        self.frame_4.raise_()
        self.logoFrame.raise_()
        self.verticalLayout_4.addWidget(self.container)
        # ===============================================================================

        self.retranslateUi(Form)
        self.minBtn.clicked.connect(Form.showMinimized)  # type: ignore
        self.exitBtn.clicked.connect(Form.close)  # type: ignore
        self.restoreBtn.clicked.connect(Form.showMaximized)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.expandBtn.setToolTip(
            _translate("Form", "<html><head/><body><p>Navigation ghost bar.</p></body></html>"))
        self.settingBtn.setToolTip(
            _translate("Form", "<html><head/><body><p>Navigation ghost bar.</p></body></html>"))
        self.appName.setText(_translate("Form", "Hospital Manager"))
        self.lineEdit.setToolTip(_translate("Form", "<html><head/><body><p>QTextBrowser</p><p><br/></p></body></html>"))
        self.calculate.setText(_translate("Form", "Calculate"))
        self.insert.setText(_translate("Form", "Insert"))
        self.show_list.setText(_translate("Form", "Show List"))
        self.data_update.setText(_translate("Form", "Data Update"))
        self.search.setText(_translate("Form", "Search"))
        self.exit.setText(_translate("Form", "Exit"))
